<?php

namespace AppBundle\Repository;

use Carbon\Carbon;

/**
 * HAccommodationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HAccommodationRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeInMonth($year, $month)
    {
        $startDate = new Carbon(sprintf('%s-%s-01 00:00:00', $year, $month));
        $endDate = Carbon::instance($startDate)->lastOfMonth();

        $this->getEntityManager()
            ->createQuery('DELETE FROM AppBundle:HAccommodation AS a WHERE a.startDate >= :startDate AND a.endDate <= :endDate')
            ->setParameters(['startDate' => $startDate->format('Y-m-d'), 'endDate' => $endDate->format('Y-m-d')])
            ->execute();
    }
}
