<?php

namespace AppBundle\Repository;

/**
 * ThirdProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThirdProviderRepository extends \Doctrine\ORM\EntityRepository
{
    public function countByType($type)
    {
        $query = $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->where('p.type = :type')
            ->setParameter('type', $type)
            ->getQuery();

        $result = $query->getResult();

        return $result[0][1];
    }
}
